apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: haproxy-cluster-role-binding-devops
 namespace: haproxy-controller-devops
roleRef:
 kind: ClusterRole
 name: haproxy-cluster-role-devops
 apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: haproxy-service-account-devops
    namespace: Haproxy-controller-devops.
    apiGroup: ""