apiVersion: v1
kind: Pod
metadata:
  name: db-pod
spec:
  containers:
    - name: mysql
      image: mysql:5.7
      env:
        - name: db-secret
          valueFrom:
            configMapKeyRef:
              name: MYSQL_DATABASE
              key: c3FsMDEK
