apiVersion: v1
kind: Pod
metadata:
  name: print-envars-greeting
spec:
  containers:
    - name: print-env-containe
      image: bash:latest
      command: 
        - sh
        - -c
      args: ["echo $GREETING $COMPANY $GROUP && sleep 3600"]
      env:
        - name: GREETING
          value: "Welcome to"
        - name: COMPANY
          value: "DevOps"
        - name: GROUP
          value: "Industries"