apiVersion: apps/v1
kind: Deployment
metadata:
  name: beta
  namespace: finance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: beta
  template:
    metadata:
      labels:
        app: beta
    spec:
      containers:
      - name: redis
        image: redis:latest
        resources:
          requests:
            memory: "1G"
            cpu: "500m"
          limits:
            memory: "2G"
            cpu: "1"