apiVersion: v1
kind: Pod
metadata:
  name: menna-nginx-podd
spec:
  containers:
  - image: nginx:latest
    name: nginx-pod-last
    volumeMounts:
      - mountPath: /etc/nginx/nginx.conf
        subPath: nginx.conf
        name: nginx-conf
  volumes:
    - name: nginx-conf
      configMap:
        name: nginx-conf