apiVersion: v1
kind: Pod
metadata:
  name: red 
spec:
  initContainers:
    - name: busybox
      image: busybox:latest
      command: ["sleep", "20"]

  containers:
    - name: redis
      image: redis:latest