apiVersion: v1
kind: Service
metadata:
  name: service-backend-devops
  namespace: haproxy-controller-devops
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      name: port-backend
      port: 80
      targetPort: 8080
  type: ClusterIP  